apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-api-configmap
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"

  Jwt__Issuer: "FCGames"
  RabbitMQ__Host: "rabbitmq"
  RabbitMQ__VirtualHost: "/"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://tempo.default:4317"

  Redis__ConnectionString: "redis:6379"
  Redis__InstanceName: "fcg:catalog:"
  Redis__DefaultTtlMinutes: "15"