apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-api-configmap
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"

  Jwt__Issuer: "FCGames"
  RabbitMQ__Host: "rabbitmq"
  RabbitMQ__VirtualHost: "/"