apiVersion: v1
kind: Secret
metadata:
  name: catalog-api-secret
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Host=;Port=;Database=;Username=;Password="
  MongoDB__ConnectionString: ""
  Jwt__SigningKey: ""
  RabbitMQ__Username: ""
  RabbitMQ__Password: ""